### ISSUE TITLE
mkdir: can't create directory '/home/qwc': Permission denied

### ISSUE THREAD

**Issue by rsrg-zwiama** [qwc-services/qwc-uwsgi-base#4]
Due to the update in the qwc-uwsgi-base commits

https://github.com/qwc-services/qwc-map-viewer/commit/a376812c04e2bbd972313c267106ec9d8eb5583d
and 
https://github.com/qwc-services/qwc-uwsgi-base/commit/7848c2868d4dc9523f941c29eaffd61456106f6b 

Pods based on the sourcepole/qwc-uwsgi-base:alpine-v2023.06.08 are failing to start when running with a user other than 0 in AKS with the error: `mkdir: can't create directory '/home/qwc': Permission denied`
Tested with  sourcepole/qwc-map-viewer-base  v2023.08.31 and sourcepole/qwc-db-auth  v2023.06.08

We run qwc-services in Azure Kubernetes Service with
``` 
 securityContext:
    runAsUser: 1012
    runAsGroup: 1012
.
.
.
  SERVICE_UID:
    value: "1012"
  SERVICE_GID:
    value: "1012"


```
Best,
Amanda
